web:
  container_name: eu_web
  build: .
  ports:
    - "8080:80"
  links:
    - db
  restart: always
  volumes:
    - .:/var/www/html
    - ~/.ssh:/root/.ssh

db:
  container_name: eu_db
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: rootpw
    MYSQL_DATABASE: EU
    MYSQL_USER: user
    MYSQL_PASSWORD: password
  restart: always
  ports:
    - "3306:3306"
  volumes: 
    - banco:/var/lib/mysql

app:
    container_name: eu_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
