web:
  build: .
  ports:
    - "8080:80"
  links:
    - db
  restart: always
  volumes:
    - .:/var/www/html
    - ~/.ssh:/root/.ssh

db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: rootpw
    MYSQL_DATABASE: EU
    MYSQL_USER: user
    MYSQL_PASSWORD: password
  restart: always
  volumes: 
    - banco:/var/lib/mysql